services:
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: app
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - CLERK_SECRET_KEY=sk_test_8LYLbrOonMrPHWF35ntrajqIvoVUrClmIy7CUs2Sii
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_ZW1pbmVudC13ZWV2aWwtOTguY2xlcmsuYWNjb3VudHMuZGV2JA
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_BE_URL=http://backend:3000

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/test
      - YOUTUBE_API_KEY=AIzaSyAESmgbt33RF4al8K2hsTYlkHR1NptJefY
      - CLERK_SECRET_KEY=sk_test_8LYLbrOonMrPHWF35ntrajqIvoVUrClmIy7CUs2Sii
      - CLERK_PUBLISHABLE_KEY=pk_test_ZW1pbmVudC13ZWV2aWwtOTguY2xlcmsuYWNjb3VudHMuZGV2JA
      - FRONTEND_URL=http://localhost:3006
      - ORIGIN=http://localhost:3006

  mongo:
    extends:
      file: ./backend/docker-compose.yml
      service: mongo

volumes:
  mongodb_data:
